roboflow:
  workspace: "cv-uoacw"
  project: "playing-cards-ow27d-5wxe0"
  version: 1
  model_format: "yolov8"
  api_key: ""

data:
  path: "Playing-Cards-1/data.yaml"

model:
  name: "yolov8n.pt"
  epochs: 100
  batch_size: 16
  imgsz: 640
  freeze: 0

wandb:
  project: "yolov8-training"
  run_name: "run-2"