roboflow:
  workspace: "cv-uoacw"
  project: "playingcarddetection-tea12-whczv"
  version: 1
  model_format: "yolov8"

data:
  path: "PlayingCardDetection-1/data.yaml"

model:
  name: "yolov8n.pt"
  epochs: 2
  batch_size: 16
  img_size: 640